import pandas as pd
from splink.duckdb.linker import DuckDBLinker
import splink.duckdb.comparison_library as cl

# 1. Load the 4 department datasets generated by Anshika
bbmp = pd.read_csv("synthetic_data/bbmp_trade_licences.csv")
escom = pd.read_csv("synthetic_data/escom_connections.csv")
labour = pd.read_csv("synthetic_data/labour_establishments.csv")
factories = pd.read_csv("synthetic_data/factories_licences.csv")

# 2. Standardize columns so they can be concatenated
def standardize(df, id_col, name_col, addr_col, source_name):
    df = df.rename(columns={
        id_col: 'unique_id',
        name_col: 'business_name',
        addr_col: 'address'
    })
    # Keep only the columns we need for matching
    df = df[['unique_id', 'business_name', 'address', 'pin_code', 'pan', 'gstin']]
    df['source_system'] = source_name
    return df

bbmp_clean = standardize(bbmp, 'trade_licence_no', 'business_name', 'business_address', 'BBMP')
escom_clean = standardize(escom, 'consumer_no', 'consumer_name', 'service_address', 'ESCOM')
labour_clean = standardize(labour, 'pf_code', 'establishment_name', 'address', 'LABOUR')
factories_clean = standardize(factories, 'factory_licence_no', 'factory_name', 'factory_address', 'FACTORIES')

# Combine them all into one master dataset
master_df = pd.concat([bbmp_clean, escom_clean, labour_clean, factories_clean], ignore_index=True)
master_df['pin_code'] = master_df['pin_code'].astype(str) # Ensure pin_code is a string

print(f"Loaded {len(master_df)} total records across 4 systems.")

# 3. Define the Splink matching logic
settings = {
    "link_type": "dedupe_only",
    "blocking_rules_to_generate_predictions": [
        "l.pin_code = r.pin_code"  # Block by Pin Code to speed up comparisons
    ],
    "comparisons": [
        cl.jaro_winkler_at_thresholds("business_name", [0.9, 0.8]), # Swapped to Jaro-Winkler
        cl.exact_match("pan"),
        cl.exact_match("gstin")
    ],
    "retain_matching_columns": True,
    "retain_intermediate_calculation_columns": True
}

# 4. Initialize Splink & Run Unsupervised Training
linker = DuckDBLinker(master_df, settings)

print("Estimating baseline probabilities...")
linker.estimate_u_using_random_sampling(max_pairs=1e6)
linker.estimate_parameters_using_expectation_maximisation("l.pin_code = r.pin_code")

# 5. Predict Matches
print("Finding candidate matches...")
# We use a low threshold (10%) just to see what the engine captures initially
predictions = linker.predict(threshold_match_probability=0.1)

# Export to CSV so Kavyansh has data to build the UI with tonight
df_predictions = predictions.as_pandas_dataframe()
df_predictions.to_csv("day1_candidate_pairs.csv", index=False)

print(f"Success! Generated {len(df_predictions)} candidate pairs and saved to day1_candidate_pairs.csv")